"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { FiEdit2, FiPlus, FiTrash2, FiUpload } from "react-icons/fi";
import Button from "@/app/components/button";
import { Modal } from "@/app/components/modal";
import { Checkbox, FormField } from "@/app/components/form-fields";
import { H3 } from "@/app/components/typography";

type Master = { id: string; name: string; isActive?: boolean };
type Asset = { url: string; storagePath: string | null };
type Config = { id: string; categoryId: string; colorId: string; frontImageUrl: string; frontStoragePath: string | null; backImageUrl: string; backStoragePath: string | null; isActive: boolean; category: Master; color: Master & { hexCode: string } };
type Form = Omit<Config, "id" | "category" | "color">;
const blank: Form = { categoryId: "", colorId: "", frontImageUrl: "", frontStoragePath: null, backImageUrl: "", backStoragePath: null, isActive: true };

export default function CustomizerProductsPage() {
  const [items, setItems] = useState<Config[]>([]); const [categories, setCategories] = useState<Master[]>([]); const [colors, setColors] = useState<(Master & { hexCode: string })[]>([]); const [form, setForm] = useState<Form>(blank); const [editing, setEditing] = useState<Config | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState<"front" | "back" | null>(null);
  const load = async () => { const [itemResponse, categoryResponse, colorResponse] = await Promise.all([fetch("/api/customizer-products", { cache: "no-store" }), fetch("/api/categories", { cache: "no-store" }), fetch("/api/colors", { cache: "no-store" })]); if (itemResponse.ok) setItems(await itemResponse.json()); if (categoryResponse.ok) setCategories((await categoryResponse.json()).filter((category: Master) => category.isActive !== false)); if (colorResponse.ok) setColors((await colorResponse.json()).filter((color: Master) => color.isActive !== false)); };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  const startCreate = () => { setEditing(null); setForm(blank); setError(""); setOpen(true); };
  const startEdit = (item: Config) => { setEditing(item); setForm({ categoryId: item.categoryId, colorId: item.colorId, frontImageUrl: item.frontImageUrl, frontStoragePath: item.frontStoragePath, backImageUrl: item.backImageUrl, backStoragePath: item.backStoragePath, isActive: item.isActive }); setError(""); setOpen(true); };
  const upload = async (side: "front" | "back", event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setUploading(side); setError(""); try { const payload = new FormData(); payload.append("images", file); const response = await fetch("/api/admin/product-images", { method: "POST", body: payload }); const data = await response.json(); if (!response.ok) throw new Error(data.error); const asset: Asset = data.images[0]; setForm((current) => side === "front" ? { ...current, frontImageUrl: asset.url, frontStoragePath: asset.storagePath } : { ...current, backImageUrl: asset.url, backStoragePath: asset.storagePath }); } catch (error) { setError(error instanceof Error ? error.message : "Image upload failed."); } finally { setUploading(null); } };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(editing ? `/api/customizer-products/${editing.id}` : "/api/customizer-products", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setOpen(false); await load(); } catch (error) { setError(error instanceof Error ? error.message : "Unable to save customizer product."); } finally { setSaving(false); } };
  const remove = async (item: Config) => { if (!confirm(`Delete ${item.category.name} / ${item.color.name}?`)) return; const response = await fetch(`/api/customizer-products/${item.id}`, { method: "DELETE" }); if (!response.ok) return setError((await response.json()).error || "Unable to delete customizer product."); await load(); };
  const imageField = (side: "front" | "back") => { const src = side === "front" ? form.frontImageUrl : form.backImageUrl; return <FormField label={`${side === "front" ? "Front" : "Back"} mockup`} required><div className="flex items-center gap-3">{src ? <img src={src} alt={`${side} mockup`} className="h-16 w-12 border border-line object-contain" /> : <div className="flex h-16 w-12 items-center justify-center border border-dashed border-line text-xs text-black/45">None</div>}<label className="secondary-button cursor-pointer"> <FiUpload /> {uploading === side ? "Uploading..." : "Upload"}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void upload(side, event)} className="hidden" disabled={Boolean(uploading)} /></label></div></FormField>; };
  return <div className="panel list-panel"><div className="page-header"><div><p className="eyebrow">Product Master</p><h1>Customizer Products</h1></div><Button onClick={startCreate}><FiPlus /> Add Configuration</Button></div>{error && <p className="form-error">{error}</p>}<div className="overflow-x-auto"><div className="min-w-[650px] divide-y divide-line">{items.length ? items.map((item) => <article key={item.id} className="grid grid-cols-[1fr_1fr_110px_auto] items-center gap-4 py-4"><H3>{item.category.name}</H3><div className="flex items-center gap-2"><span className="h-4 w-4 rounded-full border" style={{ backgroundColor: item.color.hexCode }} />{item.color.name}</div><span className="text-sm">{item.isActive ? "Active" : "Inactive"}</span><div className="item-actions"><Button variant="unstyled" size="none" aria-label="Edit configuration" onClick={() => startEdit(item)}><FiEdit2 size={16} /></Button><Button variant="unstyled" size="none" aria-label="Delete configuration" onClick={() => void remove(item)}><FiTrash2 color="red" size={16} /></Button></div></article>) : <div className="surface-message">No customizer configurations yet.</div>}</div></div><Modal open={open} title={editing ? "Edit Customizer Product" : "Add Customizer Product"} onClose={() => setOpen(false)}><form onSubmit={save} className="grid gap-4"><FormField label="Category" required><select className="w-full border border-line px-4 py-3" value={form.categoryId} onChange={(event) => setForm({ ...form, categoryId: event.target.value })} required><option value="">Select category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></FormField><FormField label="Color" required><select className="w-full border border-line px-4 py-3" value={form.colorId} onChange={(event) => setForm({ ...form, colorId: event.target.value })} required><option value="">Select color</option>{colors.map((color) => <option key={color.id} value={color.id}>{color.name}</option>)}</select></FormField><div className="grid gap-4 sm:grid-cols-2">{imageField("front")}{imageField("back")}</div><Checkbox label="Active (visible to customers)" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} />{error && <p className="form-error">{error}</p>}<div className="flex justify-end"><Button disabled={saving || Boolean(uploading)}>{saving ? "Saving..." : "Save Configuration"}</Button></div></form></Modal></div>;
}
