import { NextResponse } from "next/server";
import { Prisma, ProductStatus } from "@prisma/client";
import { getCurrentUser } from "@/lib/auth/auth";
import { prisma } from "@/lib/prisma";
function toSlug(value: string) { return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""); }
async function requireAdmin() { const user = await getCurrentUser(); return user?.role === "ADMIN" ? null : NextResponse.json({ error: user ? "Forbidden" : "Unauthorized" }, { status: user ? 403 : 401 }); }
function input(body: Record<string, unknown>) { const name = String(body.name ?? "").trim(); const categoryId = String(body.categoryId ?? ""); const price = Number(body.price); if (!name || !categoryId || !Number.isFinite(price) || price < 0) throw new Error("Name, category, and a valid price are required."); const images = Array.isArray(body.images) ? body.images.map(String).map((url) => url.trim()).filter(Boolean) : []; return { name, slug: toSlug(name), sku: String(body.sku ?? "").trim() || null, description: String(body.description ?? "").trim() || null, price: new Prisma.Decimal(price), categoryId, collectionId: String(body.collectionId ?? "") || null, status: Object.values(ProductStatus).includes(body.status as ProductStatus) ? body.status as ProductStatus : ProductStatus.DRAFT, isFeatured: Boolean(body.isFeatured), images }; }
export async function PUT(request: Request, { params }: { params: Promise<{ id: string }> }) { const error = await requireAdmin(); if (error) return error; try { const { id } = await params; const data = input(await request.json()); return NextResponse.json(await prisma.product.update({ where: { id }, data: { ...data, images: { deleteMany: {}, create: data.images.map((url, sortOrder) => ({ url, sortOrder })) } }, include: { category: true, collection: true, images: true } })); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Failed to update product." }, { status: 400 }); } }
export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { const error = await requireAdmin(); if (error) return error; const { id } = await params; await prisma.product.delete({ where: { id } }); return NextResponse.json({ success: true }); }
