import { NextResponse } from "next/server";
import { Prisma } from "@prisma/client";
import { getCurrentUser } from "@/lib/auth/auth";
import { prisma } from "@/lib/prisma";
import { removeProductImages } from "@/lib/product-images";

async function requireAdmin() { const user = await getCurrentUser(); return user?.role === "ADMIN" ? null : NextResponse.json({ error: user ? "Forbidden" : "Unauthorized" }, { status: user ? 403 : 401 }); }
function input(body: Record<string, unknown>) { const categoryId = String(body.categoryId ?? ""); const colorId = String(body.colorId ?? ""); const frontImageUrl = String(body.frontImageUrl ?? ""); const backImageUrl = String(body.backImageUrl ?? ""); if (!categoryId || !colorId || !frontImageUrl || !backImageUrl) throw new Error("Category, color, front image, and back image are required."); return { categoryId, colorId, frontImageUrl, backImageUrl, frontStoragePath: String(body.frontStoragePath ?? "") || null, backStoragePath: String(body.backStoragePath ?? "") || null, isActive: Boolean(body.isActive) }; }
const include = { category: true, color: true };
export async function PUT(request: Request, { params }: { params: Promise<{ id: string }> }) { const error = await requireAdmin(); if (error) return error; try { const { id } = await params; const existing = await prisma.customizerProduct.findUnique({ where: { id } }); if (!existing) return NextResponse.json({ error: "Customizer product not found." }, { status: 404 }); const data = input(await request.json()); const product = await prisma.customizerProduct.update({ where: { id }, data, include }); const retained = new Set([data.frontStoragePath, data.backStoragePath].filter(Boolean)); await removeProductImages([existing.frontStoragePath, existing.backStoragePath].filter((path): path is string => Boolean(path) && !retained.has(path))); return NextResponse.json(product); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return NextResponse.json({ error: "This category and color combination already exists." }, { status: 400 }); return NextResponse.json({ error: error instanceof Error ? error.message : "Failed to save customizer product." }, { status: 400 }); } }
export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { const error = await requireAdmin(); if (error) return error; const { id } = await params; const product = await prisma.customizerProduct.findUnique({ where: { id } }); if (!product) return NextResponse.json({ error: "Customizer product not found." }, { status: 404 }); await prisma.customizerProduct.delete({ where: { id } }); await removeProductImages([product.frontStoragePath, product.backStoragePath].filter((path): path is string => Boolean(path))); return NextResponse.json({ success: true }); }
